version: '3'
services:
  web:
    build: .
    ports:
      - '89:80'
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./assets:/usr/share/nginx/html/assets
      - ./forms:/usr/share/nginx/html/forms
      - ./inner-page.html:/usr/share/nginx/html/inner-page.html
